config/routes.rb
Presupuestos::Application.routes.draw do
  resources :comparas

  resources :progs

  resources :minis

  resources :deps

  resources :asientos

end

app/models/compara.rb
class Compara < ActiveRecord::Base
  belongs_to :asiento
end

app/controllers/comparas_controller.rb
class ComparasController < ApplicationController
  # GET /comparas
  # GET /comparas.xml
  def index
    @comparas = Compara.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @comparas }
    end
  end

  # GET /comparas/1
  # GET /comparas/1.xml
  def show
    @compara = Compara.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @compara }
    end
  end

  # GET /comparas/new
  # GET /comparas/new.xml
  def new
    @compara = Compara.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @compara }
    end
  end

  # GET /comparas/1/edit
  def edit
    @compara = Compara.find(params[:id])
  end

  # POST /comparas
  # POST /comparas.xml
  def create
    @compara = Compara.new(params[:compara])

    respond_to do |format|
      if @compara.save
        format.html { redirect_to(@compara, :notice => 'Compara was successfully created.') }
        format.xml  { render :xml => @compara, :status => :created, :location => @compara }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @compara.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /comparas/1
  # PUT /comparas/1.xml
  def update
    @compara = Compara.find(params[:id])

    respond_to do |format|
      if @compara.update_attributes(params[:compara])
        format.html { redirect_to(@compara, :notice => 'Compara was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @compara.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /comparas/1
  # DELETE /comparas/1.xml
  def destroy
    @compara = Compara.find(params[:id])
    @compara.destroy

    respond_to do |format|
      format.html { redirect_to(comparas_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/comparas_helper.rb
module ComparasHelper
end

app/views/comparas/_form.html.erb
<%= form_for(@compara) do |f| %>
  <% if @compara.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@compara.errors.count, "error") %> prohibited this compara from being saved:</h2>

      <ul>
      <% @compara.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :asiento_id %><br />
    <%= f.text_field :asiento_id %>
  </div>
  <div class="field">
    <%= f.label :orden %><br />
    <%= f.text_field :orden %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comparas/edit.html.erb
<h1>Editing compara</h1>

<%= render 'form' %>

<%= link_to 'Show', @compara %> |
<%= link_to 'Back', comparas_path %>

app/views/comparas/index.html.erb
<h1>Listing comparas</h1>

<table>
  <tr>
    <th>Asiento</th>
    <th>Orden</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comparas.each do |compara| %>
  <tr>
    <td><%= compara.asiento_id %></td>
    <td><%= compara.orden %></td>
    <td><%= link_to 'Show', compara %></td>
    <td><%= link_to 'Edit', edit_compara_path(compara) %></td>
    <td><%= link_to 'Destroy', compara, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Compara', new_compara_path %>

app/views/comparas/new.html.erb
<h1>New compara</h1>

<%= render 'form' %>

<%= link_to 'Back', comparas_path %>

app/views/comparas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Asiento:</b>
  <%= @compara.asiento_id %>
</p>

<p>
  <b>Orden:</b>
  <%= @compara.orden %>
</p>


<%= link_to 'Edit', edit_compara_path(@compara) %> |
<%= link_to 'Back', comparas_path %>