config/routes.rb
Presupuestos::Application.routes.draw do
  resources :comparas

  resources :progs

  resources :minis

  resources :deps

  resources :asientos

end

app/models/asiento.rb
class Asiento < ActiveRecord::Base
belongs_to :prog
belongs_to :dep
belongs_to :mini
has_one :compara
end

app/controllers/asientos_controller.rb
class AsientosController < ApplicationController
  # GET /asientos
  # GET /asientos.xml
  def index
    @asientos = Asiento.all.paginate :page => params[:page], :per_page => 20

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @asientos }
    end
  end

  # GET /asientos/1
  # GET /asientos/1.xml
  def show
    @asiento = Asiento.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @asiento }
    end
  end

  # GET /asientos/new
  # GET /asientos/new.xml
  def new
    @asiento = Asiento.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @asiento }
    end
  end

  # GET /asientos/1/edit
  def edit
    @asiento = Asiento.find(params[:id])
  end

  # POST /asientos
  # POST /asientos.xml
  def create
    @asiento = Asiento.new(params[:asiento])

    respond_to do |format|
      if @asiento.save
        format.html { redirect_to(@asiento, :notice => 'Asiento was successfully created.') }
        format.xml  { render :xml => @asiento, :status => :created, :location => @asiento }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @asiento.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /asientos/1
  # PUT /asientos/1.xml
  def update
    @asiento = Asiento.find(params[:id])

    respond_to do |format|
      if @asiento.update_attributes(params[:asiento])
        format.html { redirect_to(@asiento, :notice => 'Asiento was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @asiento.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /asientos/1
  # DELETE /asientos/1.xml
  def destroy
    @asiento = Asiento.find(params[:id])
    @asiento.destroy

    respond_to do |format|
      format.html { redirect_to(asientos_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/asientos_helper.rb
module AsientosHelper
  def busca_sub_calc (mini, prog, refe)
    sub_seccion = refe.to_s[0..0]
    items = Asiento.where("(mini_id == ?)  and 
                           (prog_id == ?) and 
                           ( substr(cast(cap_code as text),1,1) == ?)", mini,prog,sub_seccion )
    cabe =[]
    items.each do |item|
       cabe << item.desc[5..-1] if item.desc[0..4]=="TOTAL"
    end    
    [items,cabe]
  end
  def busca_item_calc(cap_code)
    cabe = []
    items = Asiento.where("cap_code == ?", cap_code)
    items.each do |item|
       cabe << item.desc[5..-1] if item.desc[0..4]=="TOTAL"
    end    
    [items,cabe]
  end
  def busca_item(asiento_or)
    items = busca_item_calc(asiento_or.cap_code)
    salida = %&<table> <h2> #{asiento_or.cap_code} <br />
              Descripcion:  #{asiento_or.desc} </h2>
              <h3> #{items[1][0]} </h3>&
    items[0].each do |item|                  
      salida += %&<tr><td><br/>
                #{item.dep.desc}</td>
                <td>#{abrev(item.mini.desc)} <br /></td>
                 <td>#{item.prog.desc}</td>
                 <td>#{item.desc}</td>
                 <td>#{item.cantidad}</td>
                 <td><a href="/asientos/#{item.id}">Mostrar</a></td></tr>&
    end
    salida += "</table>" 
  end
  def busca_sub(asiento_or) 
    items = busca_sub_calc(asiento_or.mini_id, asiento_or.prog_id, asiento_or.cap_code) 
    salida = %&<table> <h2> #{@asiento.mini.desc} <br />
              Programa:  #{@asiento.prog.desc} </h2>
              <h3> #{items[1][0]} </h3>&
    @dep_desc_old = "" 
    items[0].each do |item| 
      salida += "<tr>"
      if @dep_desc_old != item.dep.desc then 
  	    salida += %&<td><br/>
  	             <strong> #{item.dep.desc} </strong></td>
  	             </tr><tr>&
  	    @dep_desc_old = item.dep.desc 
      end 
      if @asiento.cap_code != item.cap_code then
        salida += %&<td><a href="/asientos/#{item.id}">Mostrar</a></td>&

        salida += %&<td> #{item.desc} </td>&
        if item.cap_code <1000 then 
  	      salida += "<td></td>"
  	    end 
        if item.cap_code <100 then 
  	      salida += "<td></td>"
  	    end 
        salida += "<td>"
  	    if item.cap_code <10 then 
  	      salida += "<strong> #{item.cantidad} </strong>"
        else 
          salida += item.cantidad.to_s 
        end 
        salida += "</td>"
      else
        salida += %&<td  class = "rojo"><a href = "/asientos/#{item.id}">Mostrar</a></td>&
        salida += %&<td class = "rojo"> #{item.desc} </td>&
        if item.cap_code <1000 then 
  	      salida += "<td></td>"
  	    end 	
        if item.cap_code <100 then 
  	      salida += "<td></td>"
  	    end 
        salida += %&<td class = "rojo"> #{item.cantidad} </td>&
      end 
     
      salida += "</tr>"
    end
    salida
  end
  
  def similar_cantidad_calc(id)
    ident = Asiento.find(id).compara
    @punt = ident.id.to_i
    cerca = Compara.where("id > ? and id < ?",@punt-10, @punt + 10).each{ |s| s.asiento.desc} 
    cerca   
  end
  
  def similar_cantidad(asiento_or)
    comp = similar_cantidad_calc(asiento_or.id)    
    salida = ""
    comp.each do |c|  
      if c.asiento.id == asiento_or.id then  
        salida += "<div class='rojo'> "
      end
      salida += "Cap:" + c.asiento.cap_code.to_s[0,1] + " " 
      salida += "Prog:" + c.asiento.prog.desc  + " "  
      salida +="<strong>" + abrev(c.asiento.mini.desc) + "</strong> " 
      salida += c.asiento.dep.desc  + " "  
      salida += "<i>" + c.asiento.desc + "</i> = " 
      salida += c.asiento.cantidad.to_s 
      salida += " <a href='/asientos/#{c.asiento.id}'>Mostrar</a>" + "<br />"
      if c.asiento.id == asiento_or.id then  
        salida += "</div>"
      end
    end
    salida
  end
  
  def abrev(frase)
    comunes = ["DE","E","Y","LA"]
    ab =""
    fr = frase.split(" ")
    fr.each do |palab|
      ab += palab[0,1] if  not  comunes.index(palab)
    end
    ab
  end 
  def distancia1(asiento_or)
    items = Asiento.all
    items.each do |item|
      dist = Array.new(10)
      if asiento_or.code_cap[0] == item.code_cap[0] then
        if asiento_or.code_cap.to_s.size == item.code_cap.to_s.size then
          if asiento_org.prog_id.to_s == item.code.prog_id.to_s
            puntos = 1
          end
          if asiento_or.code_cap[1] == item.code_cap[1] then 
            puntos += 2
          end
          if (asiento_or.cantidad.to_f != 0) and 
            (abs(asiento_or.cantidad - item.cantidad)/(asiento_or.cantidad < 0.01)) then
            puntos += 4
          end
          newdist=[]
          if puntos > 0 and dist[-1][1] < puntos
            dist.each do |d|
              if d[1] < puntos
                newdist << [item, puntos]
                puntos = d[1]
              end
            end
          end
        end
      end
    end
  end
        
     
     
end

app/views/asientos/_form.html.erb
<%= form_for(@asiento) do |f| %>
  <% if @asiento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@asiento.errors.count, "error") %> prohibited this asiento from being saved:</h2>

      <ul>
      <% @asiento.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :dep_id %><br />
    <%= f.text_field :dep_id %>
  </div>
  <div class="field">
    <%= f.label :cap_code %><br />
    <%= f.text_field :cap_code %>
  </div>
  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_field :desc %>
  </div>
  <div class="field">
    <%= f.label :cantidad %><br />
    <%= f.text_field :cantidad %>
  </div>
  <div class="field">
    <%= f.label :mini_id %><br />
    <%= f.text_field :mini_id %>
  </div>
  <div class="field">
    <%= f.label :prog_id %><br />
    <%= f.text_field :prog_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/asientos/edit.html.erb
<h1>Editing asiento</h1>

<%= render 'form' %>

<%= link_to 'Show', @asiento %> |
<%= link_to 'Back', asientos_path %>

app/views/asientos/index.html.erb
<h1>Listing asientos</h1>

<table>
  <tr>
    <th>Dep</th>
    <th>Cap code</th>
    <th>Desc</th>
    <th>Cantidad</th>
    <th>Mini</th>
    <th>Prog</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @asientos.each do |asiento| %>
  <tr>
	<% if not asiento.dep.nil? %>
    <td><%= asiento.dep.desc %></td>
    <% end %>
    <td><%= asiento.cap_code %></td>
    <td><%= asiento.desc %></td>
    <td><%= asiento.cantidad %></td>
	<% if not asiento.mini.nil? %>
    <td><%= asiento.mini_id %></td>
    <% end %>
	<% if not asiento.prog.nil? %>
    <td><%= asiento.prog_id %></td>
    <% end %>
    <td><%= link_to 'Show', asiento %></td>
    <td><%= link_to 'Edit', edit_asiento_path(asiento) %></td>
    <td><%= link_to 'Destroy', asiento, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />
<%= will_paginate @asientos %>

<%= link_to 'New Asiento', new_asiento_path %>

app/views/asientos/new.html.erb
<h1>New asiento</h1>

<%= render 'form' %>

<%= link_to 'Back', asientos_path %>

app/views/asientos/show.html.erb
<p id="notice"><%= notice %></p>
<strong>Dep:</strong>  <%= @asiento.dep.desc %><br />  
<strong>Cap code:</strong>  <%= @asiento.cap_code %><br />  
<strong>Desc:</strong>  <%= @asiento.desc %><br />  
<strong>Cantidad:</strong>  <%= @asiento.cantidad %><br />  
<strong>Mini:</strong>  <%= @asiento.mini.desc %><br />  
<strong>Prog:</strong>   <%= @asiento.prog.desc %><br />

<%= link_to 'Edit', edit_asiento_path(@asiento) %> |
<%= link_to 'Back', asientos_path %>

<h2>Cantidades similares</h2>
<%= similar_cantidad(@asiento).html_safe %>
<%= busca_sub(@asiento).html_safe %>
<%= busca_item(@asiento).html_safe %>