config/routes.rb
Presupuestos::Application.routes.draw do
  resources :comparas

  resources :progs

  resources :minis

  resources :deps

  resources :asientos

end

app/models/mini.rb
class Mini < ActiveRecord::Base
  has_many :asientos
end

app/controllers/minis_controller.rb
class MinisController < ApplicationController
  # GET /minis
  # GET /minis.xml
  def index
    @minis = Mini.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @minis }
    end
  end

  # GET /minis/1
  # GET /minis/1.xml
  def show
    @mini = Mini.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @mini }
    end
  end

  # GET /minis/new
  # GET /minis/new.xml
  def new
    @mini = Mini.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @mini }
    end
  end

  # GET /minis/1/edit
  def edit
    @mini = Mini.find(params[:id])
  end

  # POST /minis
  # POST /minis.xml
  def create
    @mini = Mini.new(params[:mini])

    respond_to do |format|
      if @mini.save
        format.html { redirect_to(@mini, :notice => 'Mini was successfully created.') }
        format.xml  { render :xml => @mini, :status => :created, :location => @mini }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @mini.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /minis/1
  # PUT /minis/1.xml
  def update
    @mini = Mini.find(params[:id])

    respond_to do |format|
      if @mini.update_attributes(params[:mini])
        format.html { redirect_to(@mini, :notice => 'Mini was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @mini.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /minis/1
  # DELETE /minis/1.xml
  def destroy
    @mini = Mini.find(params[:id])
    @mini.destroy

    respond_to do |format|
      format.html { redirect_to(minis_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/minis_helper.rb
module MinisHelper
end

app/views/minis/_form.html.erb
<%= form_for(@mini) do |f| %>
  <% if @mini.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mini.errors.count, "error") %> prohibited this mini from being saved:</h2>

      <ul>
      <% @mini.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :codigo %><br />
    <%= f.text_field :codigo %>
  </div>
  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_field :desc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/minis/edit.html.erb
<h1>Editing mini</h1>

<%= render 'form' %>

<%= link_to 'Show', @mini %> |
<%= link_to 'Back', minis_path %>

app/views/minis/index.html.erb
<h1>Listing minis</h1>

<table>
  <tr>
    <th>Codigo</th>
    <th>Desc</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @minis.each do |mini| %>
  <tr>
    <td><%= mini.codigo %></td>
    <td><%= mini.desc %></td>
    <td><%= link_to 'Show', mini %></td>
    <td><%= link_to 'Edit', edit_mini_path(mini) %></td>
    <td><%= link_to 'Destroy', mini, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Mini', new_mini_path %>

app/views/minis/new.html.erb
<h1>New mini</h1>

<%= render 'form' %>

<%= link_to 'Back', minis_path %>

app/views/minis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Codigo:</b>
  <%= @mini.codigo %>
</p>

<p>
  <b>Desc:</b>
  <%= @mini.desc %>
</p>


<%= link_to 'Edit', edit_mini_path(@mini) %> |
<%= link_to 'Back', minis_path %>