config/routes.rb
Presupuestos::Application.routes.draw do
  resources :comparas

  resources :progs

  resources :minis

  resources :deps

  resources :asientos

end

app/models/prog.rb
class Prog < ActiveRecord::Base
  has_many :asientos
end

app/controllers/progs_controller.rb
class ProgsController < ApplicationController
  # GET /progs
  # GET /progs.xml
  def index
    @progs = Prog.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @progs }
    end
  end

  # GET /progs/1
  # GET /progs/1.xml
  def show
    @prog = Prog.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @prog }
    end
  end

  # GET /progs/new
  # GET /progs/new.xml
  def new
    @prog = Prog.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @prog }
    end
  end

  # GET /progs/1/edit
  def edit
    @prog = Prog.find(params[:id])
  end

  # POST /progs
  # POST /progs.xml
  def create
    @prog = Prog.new(params[:prog])

    respond_to do |format|
      if @prog.save
        format.html { redirect_to(@prog, :notice => 'Prog was successfully created.') }
        format.xml  { render :xml => @prog, :status => :created, :location => @prog }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @prog.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /progs/1
  # PUT /progs/1.xml
  def update
    @prog = Prog.find(params[:id])

    respond_to do |format|
      if @prog.update_attributes(params[:prog])
        format.html { redirect_to(@prog, :notice => 'Prog was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @prog.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /progs/1
  # DELETE /progs/1.xml
  def destroy
    @prog = Prog.find(params[:id])
    @prog.destroy

    respond_to do |format|
      format.html { redirect_to(progs_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/progs_helper.rb
module ProgsHelper
end

app/views/progs/_form.html.erb
<%= form_for(@prog) do |f| %>
  <% if @prog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prog.errors.count, "error") %> prohibited this prog from being saved:</h2>

      <ul>
      <% @prog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :codigo %><br />
    <%= f.text_field :codigo %>
  </div>
  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_field :desc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/progs/edit.html.erb
<h1>Editing prog</h1>

<%= render 'form' %>

<%= link_to 'Show', @prog %> |
<%= link_to 'Back', progs_path %>

app/views/progs/index.html.erb
<h1>Listing progs</h1>

<table>
  <tr>
    <th>Codigo</th>
    <th>Desc</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @progs.each do |prog| %>
  <tr>
    <td><%= prog.codigo %></td>
    <td><%= prog.desc %></td>
    <td><%= link_to 'Show', prog %></td>
    <td><%= link_to 'Edit', edit_prog_path(prog) %></td>
    <td><%= link_to 'Destroy', prog, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Prog', new_prog_path %>

app/views/progs/new.html.erb
<h1>New prog</h1>

<%= render 'form' %>

<%= link_to 'Back', progs_path %>

app/views/progs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Codigo:</b>
  <%= @prog.codigo %>
</p>

<p>
  <b>Desc:</b>
  <%= @prog.desc %>
</p>


<%= link_to 'Edit', edit_prog_path(@prog) %> |
<%= link_to 'Back', progs_path %>